### ISSUE TITLE
Initialization not working if receiver is offline at startup

### ISSUE THREAD

**Issue by dawiinci** [foxy82/hacs-onkyo-repository#1]
If at startup of HA, the receiver is offline, the entity (mediaplayer) is not created. This leads to a missing device.

**Comment by foxy82** [comment]
Looking at the code I can see why - we query the avr in the initialization code to get some of the data. I'll have a think about how I can fix this - my AVR's are on standby all the time so i've never seen this.

**Comment by dawiinci** [comment]
Maybe just give the option do it once or have a manual refresh available. 

I don't leave it on, because of energy consumption. It would equal about 20$ a year.
