### ISSUE TITLE
Mediaplayer status stays ON if the device is offline

### ISSUE THREAD

**Issue by dawiinci** [foxy82/hacs-onkyo-repository#2]
If for example the power is cut to preserve energy (without shutting down the receiver before), the status stays on forever. Even after a restart of HA, the status stays on. The status should become off, if the device is not reachable for some time.

The original implementation reset the status at startup.

**Comment by dawiinci** [comment]
Do you use polling for the avr?

In that case you could give the option to mark it off after being offline for five minutes or so.

**Comment by dawiinci** [comment]
Could you add the possibility to set the status off manually? That would help me.

**Comment by foxy82** [comment]
Hey. Sorry I haven't had any time to really look into this. In a later version of the onkyo library they have a disconnect call back so just need to hook that in

**Comment by dawiinci** [comment]
That's great news. I'm looking forward using this version of the plugin. Hope you can fix the other issue too.
