### ISSUE TITLE
Core integration

### ISSUE THREAD

**Issue by arturpragacz** [foxy82/hacs-onkyo-repository#6]
The core integration is now completely async as well.

It might make sense to point it out in the README, so people don't think they need to use this custom integration unnecessarily.

**Comment by foxy82** [comment]
Thanks for the heads up - shame it didn't make it into the Release notes. I'll give this a go when I can and will add a notice if it works as expected.

**Comment by arturpragacz** [comment]
Any movement on this issue?

**Comment by foxy82** [comment]
I haven't had a chance to test this yet.

**Comment by Daneish** [comment]
Sound mode is supported by this integration, but is not in core yet, so it’s not quite feature parity.

**Comment by taw123** [comment]
And I believe that neither support unique IDs (needed) needed for UI config (which was part of the reason for this fork as it was hoped that would allow a decoupling of requirements that would finally allow progress from the failed CR)....  so it's still probably still useful and worth keeping to I do still have 2 bogus zones generated that I can't remove from this instance (not that I'm complaining) 😀

**Comment by arturpragacz** [comment]
This is incorrect. The core integration provides unique_id for all entities.

The sound mode support is planned, but we first need to get the config flow merged.

**Comment by taw123** [comment]
Apologies for the error and thanks for the correction. Perhaps I will move BACK to core in that it seems like dev is again progressing and might be my best option long term for addressing the extraneous zones I had generated in both integration. Do you know if there is any POTENTIAL timeframe for the sound_more support, and also for the config flow update that will have to precede it.

Thanks!

**Comment by arturpragacz** [comment]
The config flow PR is already progressing, but there is no ETA. It is all based on volunteer work, so there are no deadlines.
Once that is done, sound mode is one of the first additions planned.

**Comment by arturpragacz** [comment]
The config flow has been merged some time ago. The work on sound mode is currently ongoing.

My goal when opening this issue was to inform users on the progress that happened with the core integration. This has been open for a long time now, so I hope it has been achieved, and therefore I'm closing the issue.
